name: Main Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:    
  tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: sqlite://data.db?mode=rwc
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - uses: Swatinem/rust-cache@v1
      with:
        working-directory: ./backend
    
    - name: Install sqlx-cli
      working-directory: ./backend
      run: cargo install sqlx-cli
      
    - name: Setup backend database
      working-directory: ./backend
      run: |
        sqlx db create
        sqlx mig run
    
    - name: Run backend tests
      working-directory: ./backend
      run: cargo test
